### ISSUE TITLE
how to fix?

### ISSUE THREAD

**Issue by pa3vpat** [Poryaei/NotCoin-Clicker#1]
```
root@DanyaJsov:~/NotCoin-Clicker# python3 clicker.py
Request caused struct.error: 'i' format requires -2147483648 <= number <= 2147483647: InvokeWithLayerRequest(layer=167, query=InitConnectionRequest(api_id=6837111937, device_model='PC 64bit', system_version='5.4.0', app_version='1.33.1', system_lang_code='en', lang_pack='', lang_code='en', query=GetConfigRequest(), proxy=None, params=None))
Traceback (most recent call last):
  File "clicker.py", line 24, in <module>
    client.start()
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/auth.py", line 128, in start
    else self.loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/auth.py", line 135, in _start
    await self.connect()
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/telegrambaseclient.py", line 593, in connect
    await self._sender.send(functions.InvokeWithLayerRequest(LAYER, req))
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py", line 183, in send
    state = RequestState(request)
  File "/usr/local/lib/python3.8/dist-packages/telethon/network/requeststate.py", line 17, in __init__
    self.data = bytes(request)
  File "/usr/local/lib/python3.8/dist-packages/telethon/tl/tlobject.py", line 194, in __bytes__
    return self._bytes()
  File "/usr/local/lib/python3.8/dist-packages/telethon/tl/functions/__init__.py", line 253, in _bytes
    self.query._bytes(),
  File "/usr/local/lib/python3.8/dist-packages/telethon/tl/functions/__init__.py", line 127, in _bytes
    struct.pack('<i', self.api_id),
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<MTProtoSender._send_loop() running at /usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py:464> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7ff07aeae370>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<MTProtoSender._recv_loop() running at /usr/local/lib/python3.8/dist-packages/telethon/network/mtprotosender.py:507> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7ff07aeae070>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection._send_loop() running at /usr/local/lib/python3.8/dist-packages/telethon/network/connection/connection.py:316> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7ff07aeae250>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<Connection._recv_loop() running at /usr/local/lib/python3.8/dist-packages/telethon/network/connection/connection.py:335> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7ff07aeae2e0>()]>>
Exception ignored in: <coroutine object Connection._recv_loop at 0x7ff07aef6ec0>
RuntimeError: coroutine ignored GeneratorExit
```

**Comment by Poryaei** [comment]
you cannot pass your id as the api id. they are different things
the api id and hash comes from my.telegram.org
