### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by albert3011** [Poryaei/NotCoin-Clicker#4]
The program returns an error some time after use. Restarting the program corrects the error.

`[+] Mining 20 coins Done! New Balance: 63946
[!] Mining 20 coins field!
[~] Generating New Auth
Exception in thread Thread-1 (startMin):
Traceback (most recent call last):
  File "C:\Users\armbe\PycharmProjects\notcoin_test\.venv\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\armbe\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\armbe\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\armbe\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\armbe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\armbe\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\armbe\PycharmProjects\notcoin_test\clicker.py", line 214, in startMin
    self.webAppData = self.generateAuthToken()
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\armbe\PycharmProjects\notcoin_test\clicker.py", line 76, in generateAuthToken
    ).json()['data']['accessToken']
      ^^^^^^
  File "C:\Users\armbe\PycharmProjects\notcoin_test\.venv\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

   - OS: Windows 11
   - PyCharm

**Comment by Poryaei** [comment]
Try the new update and if you still have the same issue, let me know.
