### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by MianajiAli** [Poryaei/NotCoin-Clicker#6]
![image](https://github.com/Poryaei/NotCoin-Clicker/assets/87234097/be8b690b-6a1b-4dca-ab2a-df6f762132bb)
PS C:\Users\intel\Desktop\NotCoin-Clicker-main> python clicker.py
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Attempt 5 at connecting failed: TimeoutError: 
Attempt 6 at connecting failed: TimeoutError: 
Traceback (most recent call last):
  File "C:\Users\intel\Desktop\NotCoin-Clicker-main\clicker.py", line 23, in <module>
    client.start()
  File "C:\Users\intel\AppData\Roaming\Python\Python310\site-packages\telethon\client\auth.py", line 128, in start
    else self.loop.run_until_complete(coro)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\intel\AppData\Roaming\Python\Python310\site-packages\telethon\client\auth.py", line 135, in _start
    await self.connect()
  File "C:\Users\intel\AppData\Roaming\Python\Python310\site-packages\telethon\client\telegrambaseclient.py", line 544, in connect
    if not await self._sender.connect(self._connection(
  File "C:\Users\intel\AppData\Roaming\Python\Python310\site-packages\telethon\network\mtprotosender.py", line 134, in connect
    await self._connect()
  File "C:\Users\intel\AppData\Roaming\Python\Python310\site-packages\telethon\network\mtprotosender.py", line 260, in _connect
    raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)

**Comment by ErfanTech** [comment]
use a VPN

**Comment by Poryaei** [comment]
It looks like the connection to Telegram is failing. You could try using a VPN or proxy to resolve the issue
